---
title: "羊群效应（Herd Behavior）"
author: "赵博文"
date: "2021/10/19"
output: word_document
---
## 一、概念简述
“羊群效应”是由英国外科医生威尔弗雷德·特罗特（Wilfred Trotter）首次提出的一个术语，该词描述的是一群人在没有事先计划的情况下，通过观察别人的行为进而做出相同一致的行为。“羊群效应”也可理解为“从众心理”。从字面意思即可解释，羊群是一个散乱的整体，在放牧的过程中通常由头羊领导，这种模仿其他羊的行为就是“羊群效应”。而类似的“羊群效应”不仅在羊群可以观测到，在其他动物群以及人类中也可观察到。在体育赛事、示威和宗教集会中，这种效应尤其常见。一般来说，任何具有“羊群效应”的群体行为都需要两个组成部分：

1.个体之间的联系

2.个体之间的行为转移或观察他人行为

## 二、实例说明
### （1）晚餐的例子
假设你来到一个不熟悉的新城市，你打算选择去吃晚饭的餐厅。你在网上的餐厅推荐中看到A餐厅的评价不错，于是准备去A餐厅就餐。而当你来到A餐厅后，发现A餐厅的顾客寥寥无几。相反，附近的提供相同菜品的B餐厅却有许多人在排队。于是你选择了去B餐厅吃饭。而你之所以更改了自己原先的决定并选择B餐厅的理由，就是基于其他的顾客对A、B餐厅的选择而进行的判断。由于大部分的顾客选择了B餐厅而非A餐厅，因此你也选择了B餐厅，这就是“羊群效应”的体现。

### （2）所罗门（Solomon Asch）实验

！[图片](figure/zbw-1.png)

在所罗门实验中，所罗门把参与实验的学生分入不同的小组，组内的其他人员都是所罗门安排好的人员，然后让学生在A,B,C中选择与X线段相等的线段。所罗门发现，在没有服从压力的对照组中（即组内安排的人员给出了正确的答案），只有3%的受试者提供了错误的答案。然而当参与者被提供错误答案的人包围时，有多达32%的回答是不正确的。这个实验结果看似受到了“羊群效应”的影响，但是所罗门的实验前提仍与“羊群效应”有一些不符。与这个实验相反，“羊群效应”指的是个体通过观察其他个体的决定，有意识地做出与他人相一致的决定的过程。而在所罗门的实验中，组内其他人员的错误选择对参与者有一定的压力影响，因此该实验无法很好的说明“羊群效应”。

## 三、用贝叶斯公式解释“羊群效应”
安德森和霍尔特利用瓮实验来模拟“羊群效应”，并利用贝叶斯公式对实验的数据进行预测。该实验的具体内容如下：

### （1）实验设置
首先在瓮中盛放未知数目的红球和蓝球，让第一个学生从瓮中抽取一个球再放回，并根据自己抽中球的颜色来预测瓮内是红球多还是蓝球多，并将自己的预测答案写到黑板上，后面的学生无法得知该学生抽取球的颜色，但可以得知他的预测结果，后面的学生以此类推。

### （2）假设与分析
我们假设第一个学生抽取的颜色与预测的颜色均为蓝色，记蓝色为B，红色为R。在第一个学生抽取并预测后，黑板上的结果为【B】。第二个学生可能会选到蓝色或红色。如果是蓝色，他也预测大部分是蓝色，因为他知道之前的学生一定选择了蓝色。如果是红色，他知道第一个学生选择了蓝色，他可以随机假设大多数是红色或蓝色。所以，在第二个学生之后，我们会有【B，B】或【B,R】。我们再次假设在第二位同学预测后，黑板上的结果是【B,B】。在这种情况下，如果第三个学生拿出一个红色的球，尽管他拿到的是红球，但是他选择蓝色多的条件概率就会更高。这时“羊群效应”就发生了，我们在黑板上的结果将会变成【B,B,B】。从这个学生开始，大部分人都会预测蓝色多，而他们做出这个预测不在依赖于自己抽取球的颜色。

### （3）实验的推演
让我们根据条件概率和我们的问题设置来演示为什么会发生这种情况。在我们的问题中，我们知道第一个学生预测蓝色多的概率P（蓝色多|学生观测结果）>$\frac{1}{2}$，剩下的概率为红色多。我们也从实验设置中知道

P（蓝色多）=P（红色多）=$\frac{1}{2}$......（3.1）

P（蓝色|蓝色多）=P（红色|红色多）=$\frac{2}{3}$......（3.2）

我们假设了第一个学生观察到蓝色，于是可以得到

P（蓝色多|蓝色）=$\frac{P（蓝色|蓝色多）P（蓝色多）}{P（蓝色）}$......（3.3）

P（蓝色多）=P（蓝色|蓝色多）P（蓝色多）+P（蓝色|红色多）P（红色多） ......（3.4）

=$\frac{2}{3}$ * $\frac{1}{2}$ + $\frac{1}{3}$ * $\frac{1}{2}$=$\frac{1}{2}$......（3.5）

因此，P（蓝色多|蓝色）=$\frac{2}{3}$。所以，如果第一个学生选择蓝色，她会预测蓝色多，如果她选择红色，她会预测红色多。假设第一个学生选择蓝色，同样的论点也适用于第二个学生；如果选中蓝色，他也会预测大多数蓝色。那么 对于第三个学生，假设她选到了红色，黑板上的预测结果为【B,B】，于是

P（蓝色多|蓝色，蓝色，红色）=$\frac{P（蓝色，蓝色，红色|蓝色多）}{P（蓝色，蓝色，红色）}$ * P（蓝色多）......（3.6）

P（蓝色，蓝色，红色|蓝色多）=$\frac{2}{3}$ * $\frac{2}{3}$ * $\frac{1}{3}$ =$\frac{4}{27}$ ......（3.7）

P（蓝色，蓝色，红色）=P（蓝色，蓝色，红色|蓝色多）*P（蓝色多）+P（蓝色，蓝色，红色|红色多）*P（红色多）......（3.8）

=（$\frac{2}{3}$ * $\frac{2}{3}$ * $\frac{1}{3}$）*$\frac{1}{2}$+（$\frac{1}{3}$ * $\frac{1}{3}$ * $\frac{2}{3}$）*$\frac{1}{2}$=$\frac{1}{9}$

因此，P（蓝色多|蓝色，蓝色，红色）=$\frac{\frac{4}{27}*\frac{1}{2}}{\frac{1}{9}}$=$\frac{2}{3}$。所以，即使第三个学生选择了红色的，她的预测是蓝色多的可能性也会更大。第三个学生之后的所有学生都会预测蓝色多，无论抽到什么颜色的球，因为预测蓝色的条件保持在1/2以上。值得注意的是，瓮里实际上可能是红色的球多。例如，当前几个学生的预测结果是蓝色，蓝色，红色时，会有1−$\frac{2}{3}$=$\frac{1}{3}$的可能是红色多；然而由于“羊群效应”，这个预测可能会变得不正确。

该过程的分析示意图如下，其中矩形中的内容表示学生抽取后预测的结果，箭头旁边的字母代表学生抽取的结果。

！[图片](figure/zbw-2.png)

### （4）干预“羊群效应”
随着时间的推移，受“羊群效应”的影响学生们的判断逐渐趋于一致，下面我们将讨论如何干预此实验中的这一过程。

一般来说，可以通过向个人提供他以前不知道的私人信息来进行干预。就这个瓮实验以及我们前面的假设来说，学生们的个人预测大多是蓝色多。要想消除“羊群效应”的影响并改变其他学生的决定，要么（1）向个人传递私人信息，告知他们瓮大多是蓝色的，要么（2）在黑板上的预测结果旁边写抽取球的颜色。

## 四、“羊群效应”在实际生活中的体现
“羊群效应”最经典的体现就是在股票金融市场。在投资和股票市场，人们往往选择与大多数人的保持一致，跟风买入卖出，这也是从众心理的一种体现。还有最近正火的“双11”购物节活动，人们总是随大流地去薅各种“羊毛”，殊不知已经受到了“羊群效应”的影响，掉进了消费主义的陷阱。当这股购物热潮过去之后，清醒过来的人们才发现自己购买了许多或许没有那么需要的东西。

“羊群效应”是一种常见的心理效应，很大一部分受到“羊群效应”影响的行为都是由于没有掌握足够的信息，从而对他人的行为进行过度依赖所导致的。生活中我们要谨慎做出决定，避免受到“羊群效应”的影响导致做出后悔的行为。

## 参考文献
Zafarani R.,Abbasi M.A.,Liu H.-Social Media Mining An Induction


















