## 一、简介

  在互联网时代中，网络一直备受人们关注，随着网络的普及，我们逐渐开始了对大规模复杂网络的科学探索之旅。
  
  我们研究的许多网络都有边缘，这些边缘在网络之间形成简单的开关和连接节点。一些情况下，边缘具有强度、重量或价值，通常为实数，这表明某些边缘比其他边缘更强或更突出。
  因此在网络中边缘可能具有表示沿其流动的数据量的权值。

## 二、网络分析
  
  网络并不是我们想象中的那么支离破碎，相反他们具有很强的连通性。
在食物网中，捕食者和被捕食者之间的相互作用可能有权值来衡量它们之间的总能量流动，掠食者和猎物之间亦是如此。
在社会网络中，人和人之间也可能有权值通过交往频率来衡量亲密关系。万物皆有联系，种种联系构成关系网络最后形成复杂网络。

  度（degree）是刻画单个节点属性的基础，无向网络中节点的度定义为与节点直接相连的边的数目，
  有向网络中度分为出度（Out-degree）和入度（In-degree），而在加权网络中，它还可定义为节点的强度。
  例如，在社会网络理论中，构建人与人之间的社会关系网络，其中正面的边缘权值表示友谊或其他的亲密关系，消极关系代表着敌意。
  我们讨论这样的网络时会在边缘或节点上考虑更多的奇异变量，例如向量或离散的枚举变量，如颜色。
  由于边缘是网络研究的核心，所以在此我们主要考虑边缘的加权。网络的边可以由权值来表示，这说明某些边缘比其他的边更强或更突出。
  所以在某些情况下，它们可以用来表示边缘进行某种流动的能力，例如道路网上的最大流量和互联网的最大数据容量。
  由于要研究指定的节点对之间的最大可能流量，我们引入边割集的定义：被移除的边的集合，从网络将断开指定的节点对，最小边切集定义为一个割集，该割集各边的权值之和最小可能值。
  注意，现在最小化的不是边的数量，而是它们的权值。
  在加权网络中，两个节点之间边数最小的路径并不一定是权值之和最小的路径，且在加权有向网络中，从节点A到节点B的距离可能并不等于从B到A的距离，甚至可能并不存在从B到A的有向路径。
  有一种特殊的情况是加权的权值在所有边缘是相等的，在割集和权值的总和与简单边的数量成正比。如果加权网络中的权值都是整数，则可以创建一个具有多条边且具有完全相同邻接矩阵的网络，只需选择多重边的多重性等于相应的权值。
  
  
  
##三、例子

例如邻接矩阵   

#创建矩阵
a <- matrix(c(0,2,1,2,0,0.5,1,0.5,0),nrow = 3,ncol = 3) 
a
##      [,1] [,2] [,3]
## [1,]    0  2.0  1.0
## [2,]    2  0.0  0.5
## [3,]    1  0.5  0.0

         表示一个加权网络，其中节点1和节点2之间的连接强度是其两倍，1到3之间的强度是2到3.46之间的两倍，
         从中可以看到两种不同类型的网络，其中邻接矩阵可以有不同于0和1的非对角元素，以及带加权边的矩阵。


加权网络上的最大流量最小割集相关联，最一般形式的切定理：网络中给定节点对之间的最大流量，等于将同一两个节点分开的最小边割集的边的权值之和。
先考虑一种特殊的情况，即网络中所有边的容量都是整数乘以某个固定容量r。
然后通过替换每条边来变换我们的网络，容量kr (k为整数)由容量r的k条平行边组成。 
变换后的网络中任意两个节点之间的最大流量与原图中对应节点之间的值相同。
且变形后的网络现在具有简单非加权网络的形式，因此，从这个结果我们可以得出：网络的大小等于最小边割集的单位边的大小。  


##四、总结

通过节点和度了解了加权网络的基本内容，加权网络充分利用了网络的有向、有权信息，但是并没有很好的融合节点的其他属性，且加权矩阵的计算量大，会耗费较多的计算时间。

##五、参考文献

[1]Mark Newman.Networks: An Introduction[M].2010

[2]汪小帆，李翔，陈关荣.网络科学导论[M].2012
